"""initial schema

Revision ID: ef2d0c714fff
Revises: 
Create Date: 2026-06-22 14:57:06.491989
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef2d0c714fff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('previous_price', sa.Float(), nullable=True),
    sa.Column('price_drop_amount', sa.Float(), nullable=True),
    sa.Column('price_drop_percent', sa.Float(), nullable=True),
    sa.Column('property_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('typology', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('price_per_m2', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('has_garage', sa.Boolean(), nullable=True),
    sa.Column('has_balcony', sa.Boolean(), nullable=True),
    sa.Column('has_terrace', sa.Boolean(), nullable=True),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('energy_certificate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parish', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('municipality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('exact_location', sa.Boolean(), nullable=True),
    sa.Column('nearest_metro_station', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('distance_to_metro_m', sa.Float(), nullable=True),
    sa.Column('walking_minutes_to_metro_estimate', sa.Float(), nullable=True),
    sa.Column('rental_estimate_low', sa.Float(), nullable=True),
    sa.Column('rental_estimate_mid', sa.Float(), nullable=True),
    sa.Column('rental_estimate_high', sa.Float(), nullable=True),
    sa.Column('gross_yield_percent', sa.Float(), nullable=True),
    sa.Column('listing_agency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('delisted_at', sa.DateTime(), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('images_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('watch_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('watch_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('watch_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external_id')
    )
    op.create_index(op.f('ix_properties_delisted_at'), 'properties', ['delisted_at'], unique=False)
    op.create_index(op.f('ix_properties_distance_to_metro_m'), 'properties', ['distance_to_metro_m'], unique=False)
    op.create_index(op.f('ix_properties_external_id'), 'properties', ['external_id'], unique=False)
    op.create_index(op.f('ix_properties_gross_yield_percent'), 'properties', ['gross_yield_percent'], unique=False)
    op.create_index(op.f('ix_properties_is_active'), 'properties', ['is_active'], unique=False)
    op.create_index(op.f('ix_properties_municipality'), 'properties', ['municipality'], unique=False)
    op.create_index(op.f('ix_properties_parish'), 'properties', ['parish'], unique=False)
    op.create_index(op.f('ix_properties_price'), 'properties', ['price'], unique=False)
    op.create_index(op.f('ix_properties_price_drop_percent'), 'properties', ['price_drop_percent'], unique=False)
    op.create_index(op.f('ix_properties_price_per_m2'), 'properties', ['price_per_m2'], unique=False)
    op.create_index(op.f('ix_properties_source'), 'properties', ['source'], unique=False)
    op.create_index(op.f('ix_properties_typology'), 'properties', ['typology'], unique=False)
    op.create_index(op.f('ix_properties_watch_status'), 'properties', ['watch_status'], unique=False)
    op.create_table('refresh_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_runs_started_at'), 'refresh_runs', ['started_at'], unique=False)
    op.create_table('search_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('municipalities', sa.JSON(), nullable=False),
    sa.Column('metro_stations', sa.JSON(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('typologies', sa.JSON(), nullable=False),
    sa.Column('min_area_m2', sa.Float(), nullable=True),
    sa.Column('max_distance_to_metro_m', sa.Float(), nullable=True),
    sa.Column('require_elevator', sa.Boolean(), nullable=False),
    sa.Column('require_garage', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_property_id'), 'price_history', ['property_id'], unique=False)
    op.create_table('scores',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('price_score', sa.Float(), nullable=False),
    sa.Column('metro_score', sa.Float(), nullable=False),
    sa.Column('liquidity_score', sa.Float(), nullable=False),
    sa.Column('rental_yield_score', sa.Float(), nullable=False),
    sa.Column('condition_score', sa.Float(), nullable=False),
    sa.Column('discount_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('explanation_json', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('property_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_index(op.f('ix_price_history_property_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('search_profiles')
    op.drop_index(op.f('ix_refresh_runs_started_at'), table_name='refresh_runs')
    op.drop_table('refresh_runs')
    op.drop_index(op.f('ix_properties_watch_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_typology'), table_name='properties')
    op.drop_index(op.f('ix_properties_source'), table_name='properties')
    op.drop_index(op.f('ix_properties_price_per_m2'), table_name='properties')
    op.drop_index(op.f('ix_properties_price_drop_percent'), table_name='properties')
    op.drop_index(op.f('ix_properties_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_parish'), table_name='properties')
    op.drop_index(op.f('ix_properties_municipality'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_active'), table_name='properties')
    op.drop_index(op.f('ix_properties_gross_yield_percent'), table_name='properties')
    op.drop_index(op.f('ix_properties_external_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_distance_to_metro_m'), table_name='properties')
    op.drop_index(op.f('ix_properties_delisted_at'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
